# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               CS11
tagline:             Advanced CS
url:                 http://bsk.education/CS11
paginate:            1
baseurl:             "/CS11"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Ben Samuels-Kalow
  url:               http://bsk.education
  email:             bsk@ms224.org

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/bensk
